apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: akri
      repoURL: https://project-akri.github.io/akri/
      targetRevision: v0.12.20
      helm:
        releaseName: akri
        valueFiles:
          - $values/values.yaml
    - repoURL: "https://github.com/SP0Fs/akri-k8s.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/SP0Fs/akri-k8s.git"
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: akri
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
